// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package application

import (
	"main/model"
	"sync"
)

// Ensure, that WriterMock does implement Writer.
// If this is not the case, regenerate this file with moq.
var _ Writer = &WriterMock{}

// WriterMock is a mock implementation of Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked Writer
//		mockedWriter := &WriterMock{
//			WriteFunc: func(result []model.CompareResult) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedWriter in code that requires Writer
//		// and then make assertions.
//
//	}
type WriterMock struct {
	// WriteFunc mocks the Write method.
	WriteFunc func(result []model.CompareResult) error

	// calls tracks calls to the methods.
	calls struct {
		// Write holds details about calls to the Write method.
		Write []struct {
			// Result is the result argument value.
			Result []model.CompareResult
		}
	}
	lockWrite sync.RWMutex
}

// Write calls WriteFunc.
func (mock *WriterMock) Write(result []model.CompareResult) error {
	if mock.WriteFunc == nil {
		panic("WriterMock.WriteFunc: method is nil but Writer.Write was just called")
	}
	callInfo := struct {
		Result []model.CompareResult
	}{
		Result: result,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(result)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedWriter.WriteCalls())
func (mock *WriterMock) WriteCalls() []struct {
	Result []model.CompareResult
} {
	var calls []struct {
		Result []model.CompareResult
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
